name: Build and save my Docker image to a regitry

on:
  push:
    #paths:
     # - 'src/backend/**'  # Déclenchement lorsque le code est poussé sur main

env:
  REG_NAME: "exo.container-registry.com" # Nom du registre sans "azurecr.io"
  IMAGE_NAME: "todo-backend" # Nom de votre image dans acr

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: "exo.container-registry.com"
          username: "quentin.badoud@edufr.ch"
          password: ${{ secrets.EXO_REGISTRY_EMF }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src/backend
          push: true
          tags: exo.container-registry.com/c213-emf/todo-app-mauj:latest
 
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'wa-210-300722-mauron-julien'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_50d6ca29e3b146e49702921229be6ee9 }}
        images: 'acr300722210.azurecr.io/c213-emf/todo-app-maj:${{ github.sha }}'
