name: Build and save my Docker image to a regitry

on:
  push:
    #paths:
     # - 'src/backend/**'  # Déclenchement lorsque le code est poussé sur main

env:
  REG_NAME: "exo.container-registry.com" # Nom du registre sans "azurecr.io"
  IMAGE_NAME: "todo-backend" # Nom de votre image dans acr

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: connection to repo
        run: |
          docker login -u quentin.badoud@edufr.ch -p ${{ secrets.TOKEN }} $REG_NAME

      - name: build docker image
        working-directory: src/backend
        run: |
          docker build -t $IMAGE_NAME .


      - name: tag image
        run: |
          docker tag $IMAGE_NAME $REG_NAME/c213-emf/$IMAGE_NAME:raa

      - name: push image 
        run: |
          docker push $REG_NAME/c213-emf/$IMAGE_NAME:raa
 
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'wa-210-300722-mauron-julien'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_50d6ca29e3b146e49702921229be6ee9 }}
        images: 'acr300722210.azurecr.io/c213-emf/todo-app-maj:${{ github.sha }}'
